jobs:
  call-reusable-flow:
    secrets: inherit
    uses: camunda/automation-platform-github-actions/.github/workflows/add-issue-to-project.yml@main
    with:
      project: '40'
name: Add issue to project
on:
  repository_dispatch:
    types: trigger-ga___add-issue-to-project.yml
