jobs:
  call-reusable-flow:
    secrets: inherit
    uses: camunda/automation-platform-github-actions/.github/workflows/backport.yml@main
name: Backport merged pull request
on:
  repository_dispatch:
    types: trigger-ga___backport.yml
