jobs:
  call-reusable-flow:
    uses: camunda/automation-platform-github-actions/.github/workflows/copy-issue.yml@main
    with:
      issue: ${{ github.event.inputs.issue }}
      version: ${{ github.event.inputs.version }}
name: Copy issue
on:
  repository_dispatch:
    types: trigger-ga___copy-issue.yml
