jobs:
  call-reusable-flow:
    secrets: inherit
    uses: camunda/automation-platform-github-actions/.github/workflows/extract-issue-links.yml@main
    with:
      devex-notification-matcher: 7\.[0-9]+\.0
      devex-webhook-secret: DEVEX_CHANNEL_SLACK_WEBHOOK_URL
      sec-dri-secret: SEC_DRI_SLACK_ID
      sec-webhook-secret: SEC_CHANNEL_SLACK_WEBHOOK_URL
      support-webhook-secret: SUPPORT_CHANNEL_SLACK_WEBHOOK_URL
      translation-notification-matcher: 7\.[0-9]+\.0
      translation-webhook-secret: TRANSLATION_CHANNEL_SLACK_WEBHOOK_URL
      versions: ${{ github.event.inputs.versions }}
name: Send SUPPORT and SEC notifications
on:
  repository_dispatch:
    types: trigger-ga___extract-issue-links.yml
