jobs:
  build:
    if: ${{ github.event.label.name == 'bot:java-dependency-tree' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: camunda/java-dependency-tree-diff@main
name: Java Dependency Tree Diff
on:
  repository_dispatch:
    types: trigger-ga___java-dependency-tree.yml
