jobs:
  call-reusable-flow:
    if: ${{ github.event.label.name == 'bot:java-dependency-check' }}
    secrets: inherit
    uses: camunda/automation-platform-github-actions/.github/workflows/java-dependency-check.yml@main
    with:
      ref: main
name: Java Dependency Check
on:
  repository_dispatch:
    types: trigger-ga___java-dependency-check.yml
